### ISSUE TITLE
fragile] fragments in the handout

### ISSUE THREAD

**Issue by racke** [interchange/DBIx-Class-Training#2]
I think this line is causing the problem:

``` latex
\renewenvironment*{frame}[1]{\relax}{\relax}
```

**Comment by melmothx** [comment]
closed by 2d4912da455b32184ca8b6b9742fa7010c5c0193

**Comment by racke** [comment]
:+1: thanks for the quick fix!

**Comment by melmothx** [comment]
See https://github.com/melmothx/text-amuse/commit/af6de481778f4c55e6ee86b370bf6372ef84e50a ;-)
